### ISSUE TITLE
[FEATURE REQUEST] Captive nuts instead of heatset inserts

### ISSUE THREAD

**Issue by darigovresearch** [jpieper/bstrip#4]
We were wondering if it were possible to adjust the STL files so that they can be replaced with captive nuts instead of heatset inserts. Heatset inserts tend to be more expensive to buy and difficult to correctly insert.

Captive nuts could be the regular hexagonal ones or you can also get square ones depending on the torque requirements. Regular ones would be preferred if possible as they are easy to source.

Is this a possibility as it would greatly simplify the build?

NB: For context for anyone else who is reading this captive nuts are when there is a horizontal slot for a nut to slide in and you then screw your bolt through a designated hole.

**Comment by jpieper** [comment]
Heat set inserts have some nice properties: you can print them in more orientations than captive nuts and they also can support significantly more load and torque than a captive nut.

Have you tried inserting heat set inserts?  Once you know the trick they are trivial to do quickly and correctly.  You just need a temperature controlled soldering iron and a small flat piece of metal.  I use a 4cm x 4cm block of 6061.  You use a regular soldering iron tip set to 650F/340C to push it in 95% of the way, and let it set for 2s to heat up the plastic.  Then you press down with the flat block to force the insert in the rest of the way.  That results in it both being flush with the plastic, aligned parallel with the surface, and it flattens out any plastic that would otherwise have formed a mound around the perimeter.

In the scheme of this build, the heat set inserts are less than 1% of the total cost.  In the US at least, you can get the M3 ones from McMaster for $0.13 each https://www.mcmaster.com/94180A331/ .  Given that low relative cost and their benefits, I'm not going to switch to captive nuts.

**Comment by darigovresearch** [comment]
Yeah we agree that relative to the total cost of the BOM that in this case the cost is a very small percentage. It was just a thought that came across our mind after watching the [Index PnP build playlist](https://www.youtube.com/playlist?list=PLIeJXmcg1baLBz3x0nCDqkYpKs2IWGHk4) where he had designed some of his 3D printed parts at first to have heatset inserts but then later decided to use captive nuts at a stage when a new revision was due. It was via their channel that we heard about your project.

We're based in the UK and so even though McMaster is a great resource it takes a while to arrive if we need something in a pinch. We have tried heat set inserts but we find it difficult and hard to recover if we make a mistake which results in needing to reprint and start again which can particularly. 

No need to redesign it, just wanted to get your thoughts on the idea. You raise a good point about ability carry more load and torque. Was wondering how much load the specific heatsets need in this application. Generally speaking when using heatset inserts also need to take into account in the printing that there are enough outer shell layers and that the infill is not too sparse so it has somewhere to grip on to right?

**Comment by jpieper** [comment]
Once I got the above described trick with inserts, I've done well over 2,000 with 0 problems and they all go very quickly.

The .3mf files for bstrip all account for the inserts, but yes, you have to do at least minimal care when designing for them.  Often just using 3 perimeters is enough.

In this application I have no idea how much torque is required, and I'm glad not to have to have spent brain cycles on it!

Best of luck!
