### ISSUE TITLE
[FEATURE REQUEST] Source files for STLs

### ISSUE THREAD

**Issue by darigovresearch** [jpieper/bstrip#5]
Having the source files (depending on the accessibility of the software) would help make iterative updates to the 3D printed STL files would greatly improve the likelihood of someone being able to contribute back to the project. Such as resolving feature request #4 would be easier to tweak the source file than adjusting the STLs or reverse engineering them.

Many open source projects use FreeCAD or OpenSCAD and from experience FreeCAD is easier to use for new joiners to a project.

What did you build this project with and are you able or willing to add them to the repository?

**Comment by jpieper** [comment]
This was developed in Fusion 360.  I will post a link to a shareable version of the source in the README.  However, I'm not going to switch it to FreeCAD or OpenSCAD (although of course you're welcome to fork it and do so).  I've done a lot of work in FreeCAD in the past, and I've found that I can get things done about 90% faster in Fusion 360.  Given that when I'm working, I greatly prefer to spend my time designing things instead of futzing with the CAD tool, that's the tradeoff I'm making.

**Comment by darigovresearch** [comment]
@jpieper yeah totally agree that it's not worth your time to redo and agree that making is more important that messing with the CAD tools. We're sure the Fusion links will be beneficial to someone so thanks for making it public!
